# Generated by Django 3.2.12 on 2022-02-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='county',
            new_name='city',
        ),
    ]
