# Generated by Django 3.2.12 on 2022-02-23 15:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_rename_county_place_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title for this position')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('title', 'location'), verbose_name='Job offer address')),
                ('description', markdownx.models.MarkdownxField(blank=True, verbose_name='Description')),
                ('compensation_min', models.IntegerField(verbose_name='Min compensation')),
                ('compensation_max', models.IntegerField(verbose_name='Max compensation')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('ongoing', 'Ongoing'), ('opening soon', 'Opening Soon')], default='opening soon', max_length=12, verbose_name='Status')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.place')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
