# Generated by Django 3.2.12 on 2022-03-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_big',
            field=models.ImageField(blank=True, editable=False, upload_to='blog/thumbs/big/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=9, verbose_name='Status'),
        ),
    ]
